version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    environment:
      - FLASK_DEBUG=False
      - PORT=5000 